### ISSUE TITLE
ClientSecret and ClientID ?

### ISSUE THREAD

**Issue by grangej** [melgu/TidalSwift#10]
I am trying to write my own client , where did you get this information from ?

**Comment by melgu** [comment]
I captured the network traffic while using the official Tidal app using a proxy.

Although the most current ClientSecret is from another GitHub member if I remember correctly.

**Comment by grangej** [comment]
Interesting , so everyone is more or less sharing the same client secret across the community? 😬

**Comment by melgu** [comment]
Yes, pretty much, as far as I know 😄
The current secret came from this PR: #7

**Comment by grangej** [comment]
Ok so be it, I did also request to join tidal connect, let's see if they approve me hah

**Comment by melgu** [comment]
Good luck 🍀
