### ISSUE TITLE
Want some free TIDAL to continue this?

### ISSUE THREAD

**Issue by ElbowBaggins** [melgu/TidalSwift#13]
I have a family TIDAL account with several slots still free. I'd be glad to throw one your way if it helps keep this project alive. Not sure where else I could have posted this, so, here it is! Just reply to this issue and we can sync up on Discord or something. The email address on my profile page is also a good place to reach me.

**Comment by melgu** [comment]
Hi! Thanks for the initiative. That would be really helpful!
You can reach me via email (mail@melvin-gundlach.de). That's probably the easiest way to keep in touch.

**Comment by tmikaeld** [comment]
I'm super happy that you're back at it! 

I hope you'll get it up on the app store or setapp stores too, so I can pay for it's continuation.

**Comment by melgu** [comment]
That would be cool, but is probably out of the question since I don't and probably never will have a usage agreement with Tidal.
So I have to rely on GitHub sponsorships.

**Comment by Lucyy-cloud** [comment]
Whether you use the free version of Tidal or subscribe to HiFi or HiFi Plus on Tidal, you can use [Tunelf Tidal Music Converter](https://www.tunelf.com/tidal-music-converter.html) to download music from Tidal for free while retaining lossless audio quality.
