### ISSUE TITLE
Latest release?

### ISSUE THREAD

**Issue by jacksongoode** [melgu/TidalSwift#14]
Just wondering if you will continue releasing builds or if it would make sense to show how folks could minimally build this app?

**Comment by melgu** [comment]
It’s definitely a good idea to add a section to the README on how to build the project. Basically you need to clone or download the repository, open the project in Xcode and change the developer account to your own.

I’ll also create a new build, now that I am at least somewhat working on it.

**Comment by jacksongoode** [comment]
Okay great! Thanks!

**Comment by jacksongoode** [comment]
Just wondering if you're around to run a release?

**Comment by melgu** [comment]
Hi! I just released a [new version](https://github.com/melgu/TidalSwift/releases), that should fix the login and several smaller issues. Let me know if it works for you.
