### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by raff** [melgu/TidalSwift#3]
It would be possible to add building instructions ?

I tried to build but:
- I got errors fetching required packages (I had to replace the git@github.com:  in the required URIs with https://github.com/)
- I had to install (via brew) the mp4v2 package
- I am still getting error importing mp4v2 in MP42-Swift.h:
`
  @import mp4v2; // Module 'mp4v2' not found
`

**Comment by melgu** [comment]
Which version of Xcode and macOS and which architecture (Intel / M1) are you using?

**Comment by raff** [comment]
MacOS 11.2 Intel, Xcode 12.3

**Comment by melgu** [comment]
This is quite strange.
* ssh or https doesn't make a difference on GitHub, if SSH is setup properly.
* Installing mp4v2 shouldn't be necessary, as I don't have it installed.
* For the MP42Foundation framework I just copied the result after building the [respective project](https://bitbucket.org/galad87/mp42foundation/src/master/). The build is included in the TidalSwift project.

If you want to just run TidalSwift, you can download the latest version [here](https://github.com/melgu/TidalSwift/releases).
