### ISSUE TITLE
Binary package

### ISSUE THREAD

**Issue by andrusz** [melgu/TidalSwift#4]
Hi, 

Where can I find Mac binary (dmg) file? Or need to compile it myself?

Regards,
Marek

**Comment by melgu** [comment]
In the [releases section](https://github.com/melgu/TidalSwift/releases/tag/0.1-40).
After downloading it and putting it in your applications folder, you might need to start it via right click -> Open for the first time to tell Gate Keeper to allow it. Alternatively you can allow it in the system settings after it warns you the first time.
