### ISSUE TITLE
Support for MacOS High Sierra?

### ISSUE THREAD

**Issue by donmega** [melgu/TidalSwift#5]
Hi,

I know High Sierra is unsupported, but i was wondering if there is a possibility to add suport for High Sierra.
Thanks, and keep up the great job!

**Comment by melgu** [comment]
Hi! The whole TidalSwift UI is written in SwiftUI and is therefore limited to macOS 10.15 (Catalina) and up.

**Comment by donmega** [comment]
Thanks for the fast reply! It's running great on my main Catalina machine, so keep up the great job!

**Comment by melgu** [comment]
Thanks for the encouraging words. Glad you like it 😊
