### ISSUE TITLE
"My Mixes" issue

### ISSUE THREAD

**Issue by Zlodiar** [melgu/TidalSwift#6]
![image](https://user-images.githubusercontent.com/90006848/135717186-9ec2315a-2863-407d-bc17-a9bdc741ca31.png)

Everything goes just perfect except "My Mixes"  feature. Can you fix this issue?

**Comment by melgu** [comment]
Thanks for bringing it to my attention. Just fixed it in [0.1 (46)](https://github.com/melgu/TidalSwift/releases/tag/0.1-46).

**Comment by Zlodiar** [comment]
Can't believe my eyes! Bro you made fantastic job, you know. Your app right now beats other Tidal-supported apps ass. Trust me. More than two years since i moved to mac os i try to find real alternative to official monster-app. Can't wait to see how you beat next huge goal - Tidal Menu Bar Player w/album art work !
